
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alejo
 */
public class Predictor extends javax.swing.JFrame {

    /**
     * Creates new form Predictor
     */
    public Predictor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Predictor de texto");

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Sugerencias "
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     * @throws java.io.IOException
     */
    
    
    static void CrearArchivo() throws IOException{
        String ruta = "C:/apps/vocabulario.txt";
        File vocabulario = new File(ruta);
        BufferedWriter bw;
        if(vocabulario.exists()) {
            bw = new BufferedWriter(new FileWriter(vocabulario));
            bw.write("El archivo de texto ya estaba creado.");
        } else {
            bw = new BufferedWriter(new FileWriter(vocabulario));
            bw.write("Abordar, Abrumar, Abstenerse, Acápite, Acatar, Accesorio, Acicalarse, Acopio, Acoso, \n" +
"Acotación, Acrecienta, Acróstico, Acta, Actitud, Bambolearse, Bastante, Beluga, \n" +
"Bifurcación, Biografía, Bitácora, Bocanada, Borda, Bosquejo, Brahmán, Brainstorm, \n" +
"Bronca, Burladero, Butaca, Caldear, Calidad total, Candente, Camaleón, Caos, \n" +
"Capciosas, Capitalizar, Capo di capi, Característica, Carisma, Denostar, \n" +
"Denotando, Derecho, Desabrido, Desliz, Destaca, Detractores, Dexteridad,\n" +
"Diapositiva, Efecto, Eficaz, Eficiente, Egocentrista,Egoísta, Egolatría, Ejecutivo,\n" +
"Factor, Falacia, Falta de tacto, Familia, Fanfarrón, Fe,Habla, Heces, Hedonista, \n" +
"Heurístico, Hipersensibilidad, Hipnotizador, Idiosincrasia, Idóneo, Ilusión,\n" +
"Ilustración, Ilustrar, Impecable, Impertérrito, Impertinente, Implantar, Implosión,\n" +
"Jerarquía, John, Jubilación, Karate, Kinestésico, Know how, Latente, Laudable, \n" +
"Legítimo, Libreto, Lidiar, Limadura de hierro, Maquiavélico, Marketing, Masoquismo,\n" +
"Mayéutica, Mediático, Mediocre, Menoscabar, Mente maestra, Metafísico, Metafórico,\n" +
"Nanómetro, NASA, Nefasto, Nemotecnia, Nequáquam, Nimio, Objeción, Objetivo, \n" +
"Obnubilar, Obvio, Oclusivo, Oír, Patente, Patético, Pausa, Pauta, Pecado, \n" +
"Pedante, Péndulo, Penetrantes, Pericia, Perorata, Quid, Quid pro quo, \n" +
"Radio, Rangos, Reacio, Recargarse, Reconciliación, Referencia,Reflexión,\n" +
"Refranes, Refutar, Reglamento, Sabiduría, Sadismo, Sánscrito, Savoir-faire,\n" +
"Secoya, Secuencia, Seminario, Táctica, Técnica, Teleológico, Tema, Tener, Traducir,\n" +
"Urbanidad, URL, Utópico, Valor añadido, Valores, Verbal, Verborrea, Verificando, \n" +
"Versátil, Viceversa, Vídeo, Vigorosamente, Web, Webmaster, Yen, Yuan");
        }
        bw.close();
        
        
          BufferedReader br = new BufferedReader(new FileReader (ruta));

         String linea;
         String Palabras[] = vocabulario.list();
         while((linea=br.readLine())!=null)
            System.out.println(linea);
      
        br.close();
    }
    public static void main(String args[]) throws IOException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Predictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Predictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Predictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Predictor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Predictor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
